name: Generate Snake Animation

on:
  schedule:
    # Run once every 24 hours
    - cron: "0 0 * * *"
  
  # Allow manual execution of this workflow
  workflow_dispatch:
  
  # Run on every push to main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Generates a snake game from a github user contributions graph, output a svg animation at <summary_output_path>
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Push the content of <build_dir> to a branch
      # The content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>
      - name: Push github-contribution-grid-snake.svg to GitHub Pages / Output Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
